---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: ndb-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ndb-operator
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs:
      - get
      - list
      - update
      - watch

    - apiGroups: [""]
      resources: ["configmaps"]
      verbs:
      - get
      - list
      - update
      - create
      - watch

    - apiGroups: [""]
      resources: ["services"]
      verbs:
      - get
      - list
      - update
      - create
      - watch

    - apiGroups: ["apps"]
      resources: ["statefulsets"]
      verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch

    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch

    - apiGroups: ["policy"]
      resources: ["poddisruptionbudgets"]
      verbs:
      - create
      - get
      - list
      - watch

    - apiGroups: ["mysql.oracle.com"]
      resources:
      - ndbs
      verbs:
      - get
      - list
      - patch
      - update
      - watch
  
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ndb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ndb-operator
subjects:
- kind: ServiceAccount
  name: ndb-operator
  namespace: default
