---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: ndb-agent
    namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ndb-agent
    namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs:
      - get
      - list
      - patch
      - update
      - watch

    - apiGroups: [""]
      resources: ["endpoints"]
      verbs:
      - get
      - list
      - patch
      - update
      - watch

    - apiGroups: ["apps"]
      resources: ["statefulsets"]
      verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch

    - apiGroups: ["mysql.oracle.com"]
      resources:
      - ndbs
      verbs:
      - get
      - list
      - patch
      - update
      - watch
  
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ndb-agent
    namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ndb-agent
subjects:
- kind: ServiceAccount
  name: ndb-agent
  namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
