---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: ndb-operator
    namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ndb-operator
    namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs:
      - get
      - list
      - update
      - watch

    - apiGroups: [""]
      resources: ["configmaps", "services"]
      verbs:
      - get
      - list
      - update
      - create
      - watch

    - apiGroups: [""]
      resources: ["secrets"]
      verbs:
      - get
      - create

    - apiGroups: [""]
      resources: ["events"]
      verbs:
      - create
      - patch

    - apiGroups: ["apps"]
      resources: ["statefulsets", "deployments"]
      verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch

    - apiGroups: ["policy"]
      resources: ["poddisruptionbudgets"]
      verbs:
      - create
      - get
      - list
      - watch

    - apiGroups: ["mysql.oracle.com"]
      resources:
      - ndbs
      - ndbs/status
      verbs:
      - get
      - list
      - patch
      - update
      - watch
  
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ndb-operator
  namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ndb-operator
subjects:
- kind: ServiceAccount
  name: ndb-operator
  namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
