# Service account for webhook server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ndb-operator-webhook-sa
  namespace: {{.Release.Namespace}}
---
# Service Account for Ndb Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ndb-operator-sa
  namespace: {{.Release.Namespace}}
