# Service account for webhook server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ndb-operator-webhook-sa
  namespace: {{.Values.operator.namespace}}
---
# Service Account for Ndb Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ndb-operator-sa
  namespace:  {{ if and (.Values.operator.global) (eq .Values.operator.namespace "ndb-operator") }}ndb-operator{{ else }}{{ .Values.operator.namespace}}{{ end }}
