apiVersion: v1
kind: Secret
metadata:
  name: ndbop-mysql-secret
# Can use kubernetes.io/basic-auth type secret as well
type: Opaque
stringData:
  # password key is mandatory.
  # Everything else is ignored by the operator
  password: ndbpass
---
apiVersion: mysql.oracle.com/v1alpha1
kind: Ndb
metadata:
  name: example-ndb
spec:
  containerImage: mysql/mysql-cluster:8.0.22
  nodeCount: 2
  redundancyLevel: 2
  mysqld:
    nodeCount: 2
    rootPasswordSecretName: ndbop-mysql-secret
