apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ndbs.mysql.oracle.com
spec:
  group: mysql.oracle.com
  names:
    kind: Ndb
    plural: ndbs
  scope: Namespaced
  versions: 
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: "Ndb is the Schema for the Ndb's API"
          type: object
          properties:
            spec:
              description: 'NdbSpec defines the desired state of MySQL Ndb Cluster.'
              type: object
              properties:
                containerImage:
                  description: ContainerImage is the name of the MySQL Ndb Cluster image to be used. 
                    If not otherwise specified "mysql-cluster:latest" will used. 
                    Lowest supported version is 8.0.22.
                  type: string
                nodecount: 
                  description: "nodeCount is the total number of data nodes in cluster. The node count 
                    needs to be a multiple of the redundancyLevel. Currently the maximum is 144 data nodes."
                  type: integer
                  format: uint8
                  minimum: 1
                  maximum: 144
                redundancyLevel:
                  description: 'The number of data replicas or copies of data stored in Ndb Cluster.  
                    Supported and allowed values are 1, 2, 3, and 4.
                    A reduncancy level of 1 creates a sharded cluster providing NO fault tolerance 
                    in case of node failure.
                    With a reduncancy level of 2 or higher cluster will continue serving client requests 
                    even in case of failures. 2 is the normal and most common value and the default.
                    A 3-replica cluster provides additional protection.

                    For a reduncancy level of 1 one management server will be created. For 2 or higher
                    two management servers will be used.

                    Once a cluster has been created, this number can NOT be easily changed.'
                  type: integer
                  format: uint8
                  minimum: 1
                  maximum: 4
                mysqld:
                  description: Mysqld describes how MySQL Servers will be added to Ndb Cluster as a SQL frontend.
                  type: object
                  properties:
                    nodecount: 
                      description: NodeCount is the number of MySQL Servers running in MySQL Cluster.
                      type: integer
                      format: uint8
            status:
              type: object
              properties:
                lastUpdate:
                  type: string
                processedGeneration:
                  type: integer  
                receivedConfigHash:
                  type: string